# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: enclaveOperations.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'enclaveOperations.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x65nclaveOperations.proto\"@\n\x16UserCredentialsRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x14\n\x0c\x61\x63\x63\x65ss_token\x18\x02 \x01(\t\"\xe6\x01\n\x15\x45nclaveLaunchResponse\x12\x14\n\x0c\x65nclave_name\x18\x01 \x01(\t\x12\x14\n\x0c\x61\x63\x63\x65ss_point\x18\x02 \x01(\t\x12\x1c\n\x0ftls_certificate\x18\x03 \x01(\x0cH\x00\x88\x01\x01\x12#\n\x16public_attestation_key\x18\x04 \x01(\x0cH\x01\x88\x01\x01\x12!\n\ttpm_quote\x18\x05 \x01(\x0b\x32\t.TpmQuoteH\x02\x88\x01\x01\x42\x12\n\x10_tls_certificateB\x19\n\x17_public_attestation_keyB\x0c\n\n_tpm_quote\"/\n\x15\x45nclaveStatusResponse\x12\x16\n\x0e\x65nclave_status\x18\x01 \x01(\t\";\n\x08TpmQuote\x12\x1c\n\x14tls_certificate_hash\x18\x01 \x01(\t\x12\x11\n\tsignature\x18\x02 \x01(\x0c\x32\x97\x01\n\x11\x45nclaveOperations\x12@\n\rEnclaveLaunch\x12\x17.UserCredentialsRequest\x1a\x16.EnclaveLaunchResponse\x12@\n\rEnclaveStatus\x12\x17.UserCredentialsRequest\x1a\x16.EnclaveStatusResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'enclaveOperations_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USERCREDENTIALSREQUEST']._serialized_start=27
  _globals['_USERCREDENTIALSREQUEST']._serialized_end=91
  _globals['_ENCLAVELAUNCHRESPONSE']._serialized_start=94
  _globals['_ENCLAVELAUNCHRESPONSE']._serialized_end=324
  _globals['_ENCLAVESTATUSRESPONSE']._serialized_start=326
  _globals['_ENCLAVESTATUSRESPONSE']._serialized_end=373
  _globals['_TPMQUOTE']._serialized_start=375
  _globals['_TPMQUOTE']._serialized_end=434
  _globals['_ENCLAVEOPERATIONS']._serialized_start=437
  _globals['_ENCLAVEOPERATIONS']._serialized_end=588
# @@protoc_insertion_point(module_scope)
