---

services:
  svc-auth:
    build: .
    ports:
      - "45000:45000"
    depends_on:
      - svc-db
    environment:
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_HOST: svc-db
      DATABASE_PORT: 5432
      DATABASE_NAME: userdb
      JWT_SECRET_KEY: SEszq324cdSZ

  svc-db:
    image: postgres:13
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: userdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_MAX_CONNECTIONS: 3
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      retries: 5
