# Role for managing pods, namespaces, and secrets
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-secret-namespace-manager
  namespace: tpm
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "create", "update", "delete", "watch"]
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "list", "create", "update", "delete"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "create", "update", "delete"]
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["rolebindings"]
  verbs: ["list", "get"]

---
# RoleBinding to bind the Role to the default ServiceAccount
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: default-serviceaccount-manager
  namespace: tpm
subjects:
- kind: ServiceAccount
  name: default
  namespace: tpm
roleRef:
  kind: Role
  name: pod-secret-namespace-manager
  apiGroup: rbac.authorization.k8s.io
