apiVersion: apps/v1
kind: Deployment
metadata:
  name: enclave-postgres
  namespace: tpm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: enclave-postgres
  template:
    metadata:
      labels:
        app: enclave-postgres
    spec:
      containers:
      - name: postgres
        image: postgres:13
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_HOST_AUTH_METHOD
          value: "trust"
        - name: POSTGRES_DB
          value: userdb
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: postgres
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
        readinessProbe:
          exec:
            command: ["pg_isready", "-U", "postgres"]
          periodSeconds: 5
          failureThreshold: 5
        resources: # Moved resources block inside the container
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: svc-postgres
  namespace: tpm
spec:
  selector:
    app: enclave-postgres
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: tpm
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 128Mi
